// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp.net_Project.Models;

#nullable disable

namespace asp.net_Project.Migrations
{
    [DbContext(typeof(StepsDbContext))]
    partial class StepsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asp.net_Project.Models.StepsModel", b =>
                {
                    b.Property<DateTime>("dates")
                        .HasColumnType("datetime2");

                    b.Property<int>("stepsNum")
                        .HasColumnType("int");

                    b.HasKey("dates");

                    b.ToTable("StepsM");
                });
#pragma warning restore 612, 618
        }
    }
}
